CREATE DATABASE IF NOT EXISTS HOSPITAL;

USE HOSPITAL;

CREATE TABLE IF NOT EXISTS ADMINISTRADOR(
id_admin VARCHAR(50) NOT NULL, 
dpi VARCHAR(30) NOT NULL,
nombre VARCHAR(75) NOT NULL,
CONSTRAINT PK_ID_ADMIN PRIMARY KEY(id_admin)
);

CREATE TABLE IF NOT EXISTS USUARIO(
id_user VARCHAR(50) NOT NULL,
nombre VARCHAR(75) NOT NULL,
rol VARCHAR(75) NOT NULL,
pass VARCHAR(75) NOT NULL,
CONSTRAINT PK_ID_USER PRIMARY KEY(id_user)
);

INSERT INTO ADMINISTRADOR VALUES('AD1','123456789101112','JUAN PACO PEDRO DE LA MAR');
INSERT INTO USUARIO VALUES('AD1','JUAN PACO PEDRO DE LA MAR','ADMINISTRADOR','ASDF1234');

INSERT INTO ADMINISTRADOR VALUES(1231,'416904550','JAMES RANDY VASQUEZ GUZMAN');
INSERT INTO USUARIO VALUES(1231,'JAMES RANDY VASQUEZ GUZMAN','ADMINISTRADOR','ASDF1234');

CREATE TABLE IF NOT EXISTS PACIENTE(
id_paciente INT AUTO_INCREMENT NOT NULL,
nombre VARCHAR(75) NOT NULL,
sexo VARCHAR(20) NOT NULL,
fecha_nacimiento DATE NOT NULL,
dpi VARCHAR(30) NOT NULL,
telefono VARCHAR(50) NOT NULL,
peso DECIMAl(65,2) NOT NULL,
tipo_sangre VARCHAR(20) NOT NULL,
correo VARCHAR(75) NOT NULL,
CONSTRAINT PK_ID_PACIENTE PRIMARY KEY(id_paciente)
);

INSERT INTO PACIENTE VALUES(177840,'Mario Diaz','Hombre','1990-1-1','89505278065','50422898',70,'A-','mail2848@othermail.com');
INSERT INTO USUARIO VALUES(177840,'Mario Diaz','PACIENTE','K^4U;q>=nx5WE954');

INSERT INTO PACIENTE VALUES(118258,'Lucia Coti','Mujer','2018-5-15','78207368533','57635181',22,'0+','mail1031@othermail.com');
INSERT INTO USUARIO VALUES(118258,'Lucia Coti','PACIENTE','jd8Mp"vN{BG[WL:b');

INSERT INTO PACIENTE VALUES(56543,'Dulce Cayax','Mujer','1997-4-25','60950626066','19131386',45,'A+','mail8926@othermail.com');
INSERT INTO USUARIO VALUES(56543,'Dulce Cayax','PACIENTE','8!EM;g}g3mQ"Y+');

CREATE TABLE IF NOT EXISTS DOCTOR(
id_doctor VARCHAR(50) NOT NULL,
nombre VARCHAR(75) NOT NULL,
colegiado VARCHAR(20) NOT NULL,
dpi VARCHAR(25) NOT NULL,
telefono VARCHAR(50) NOT NULL,
correo VARCHAR(75) NOT NULL,
hora_inicio TIME NOT NULL,
hora_fin TIME NOT NULL,
fecha_inicio DATE NOT NULL,  
CONSTRAINT PK_ID_DOCTOR PRIMARY KEY(id_doctor)
);

CREATE TABLE IF NOT EXISTS ESPECIALIDAD(
id_especialidad INT AUTO_INCREMENT NOT NULL,
id_doctor VARCHAR(50) NOT NULL,
tipo_especialidad VARCHAR(75) NOT NULL,
CONSTRAINT PK_ID_ESPECIALIDAD PRIMARY KEY(id_especialidad),
CONSTRAINT FK_ID_DOCTOR FOREIGN KEY(id_doctor)
REFERENCES DOCTOR(id_doctor)
);

CREATE TABLE IF NOT EXISTS LABORATORISTA(
id_labo VARCHAR(50) NOT NULL,
nombre VARCHAR(75) NOT NULL,
registro VARCHAR(50) NOT NULL,
dpi VARCHAR(25) NOT NULL,
telefono VARCHAR(50) NOT NULL,
examen VARCHAR(75) NOT NULL,
correo VARCHAR(75) NOT NULL,
fecha_inicio DATE NOT NULL,
CONSTRAINT PK_ID_LABO PRIMARY KEY(id_labo)
);

CREATE TABLE IF NOT EXISTS DIAS_LABORATORISTA(
id_diaslabo INT AUTO_INCREMENT NOT NULL,
id_labo VARCHAR(50) NOT NULL,
dia_trabajo VARCHAR(50) NOT NULL,
CONSTRAINT PK_ID_DIASLABO PRIMARY KEY(id_diaslabo),
CONSTRAINT FK_ID_LABO FOREIGN KEY(id_labo)
REFERENCES LABORATORISTA(id_labo)
);

CREATE TABLE IF NOT EXISTS EXAMEN(
id_examen VARCHAR(30) NOT NULL,
nombre VARCHAR(75) NOT NULL,
orden BOOLEAN NULL,
descripcion VARCHAR(300) NOT NULL,
costo DECIMAL(65,2) NOT NULL,
tipo_informe VARCHAR(15) NOT NULL,
CONSTRAINT PK_ID_EXAMEN PRIMARY KEY(id_examen)
);

CREATE TABLE IF NOT EXISTS AGENDAR_EXAMEN(
id_agex INT AUTO_INCREMENT NOT NULL,
id_exam VARCHAR(30) NOT NULL,
id_dctr VARCHAR(50) NULL DEFAULT 'NO SE EMITIO POR NINGUN DOCTOR',
id_pcnt INT NOT NULL,
fecha DATE NOT NULL,
requiere LONGBLOB NULL,
CONSTRAINT PK_ID_AGEX PRIMARY KEY(id_agex),
CONSTRAINT FK_ID_EXAM FOREIGN KEY(id_exam)
REFERENCES EXAMEN(id_examen),
CONSTRAINT FK_ID_PCNT FOREIGN KEY(id_pcnt)
REFERENCES PACIENTE(id_paciente)
);

CREATE TABLE IF NOT EXISTS RESULTADO(
id_resultado INT AUTO_INCREMENT NOT NULL,
id_agex INT NULL,
id_paciente INT NOT NULL,
id_medico VARCHAR(50) NOT NULL,
id_examen VARCHAR(30) NOT NULL,
id_laboratorista VARCHAR(50) NOT NULL,
orden VARCHAR(100) NULL,
informe LONGBLOB NULL,
fecha DATE NOT NULL,
hora TIME NOT NULL,
CONSTRAINT PK_ID_RESULTADO PRIMARY KEY(id_resultado),
CONSTRAINT FK_ID_PACIENTE FOREIGN KEY(id_paciente)
REFERENCES PACIENTE(id_paciente),
CONSTRAINT FK_ID_LABORATORISTA FOREIGN KEY(id_laboratorista)
REFERENCES LABORATORISTA(id_labo),
CONSTRAINT FK_ID_EXAMEN FOREIGN KEY(id_examen)
REFERENCES EXAMEN(id_examen)
);

CREATE TABLE IF NOT EXISTS CONSULTA(
especialidad VARCHAR(100) NOT NULL,
costo DECIMAL(65,2) NOT NULL,
CONSTRAINT PK_ESPECIALIDAD PRIMARY KEY(especialidad)
);

CREATE TABLE IF NOT EXISTS CITA(
id_cita INT AUTO_INCREMENT NOT NULL,
id_pacnt INT NOT NULL,
id_doc VARCHAR(50) NOT NULL,
especialidad VARCHAR(50) NOT NULL,
fecha DATE NOT NULL,
hora TIME NOT NULL,
CONSTRAINT PK_ID_CITA PRIMARY KEY(id_cita),
CONSTRAINT FK_ID_PACNT FOREIGN KEY(id_pacnt)
REFERENCES PACIENTE(id_paciente),
CONSTRAINT FK_ID_DOC FOREIGN KEY(id_doc)
REFERENCES DOCTOR(id_doctor)
);

CREATE TABLE IF NOT EXISTS INFORME(
id_informe INT AUTO_INCREMENT NOT NULL,
id_pac INT NOT NULL,
id_dct VARCHAR(50) NOT NULL,
info VARCHAR(300) NOT NULL,
fecha DATE NOT NULL,
hora TIME NOT NULL,
CONSTRAINT PK_ID_INFORME PRIMARY KEY(id_informe),
CONSTRAINT FK_ID_PAC FOREIGN KEY(id_pac)
REFERENCES PACIENTE(id_paciente),
CONSTRAINT FK_ID_DCT FOREIGN KEY(id_dct)
REFERENCES DOCTOR(id_doctor)
);
